### ISSUE TITLE
Blinding?

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/txpipe-reanalysis#1]
From Troxel: "Does DESC have a blinding policy that will guide these measurements/constraints? We are working with state-of-the-art data now, and the results will be meaningful and should be properly blinded. "

Let's discuss where and when and how we want to blind.

**Comment by EiffL** [comment]
That's a very good point... but that will require a fair amount of more thinking than I was expecting for this project. 
I'm all for blinding though, and I guess the sooner we start putting the infrastructure and method in place the better. 
@joezuntz do you have thoughts on where when and how to incorporate some blinding strategies in TXPipe?

**Comment by joezuntz** [comment]
This is a very good point.  We could incorporate it either in the 2pt estimation functions themselves, or add a blinding stage following on from them I guess.  In terms of methodology - the one presented in Muir et al recently is very nice as it can be applied to any statistic we calculate.

**Comment by chihway** [comment]
Let's default to apply the Muir et al. blinding (which we'd need to incorporate into TXPipe) if we don't have a clear, better alternative.

**Comment by chihway** [comment]
Starting a branch in TXPipe to incorporate this `blinding`. To incorporate Muir et al. method we would need to interface with CCL. Let's plan on doing this from the start. In order to not slow down the development too much, I'll have two options for blinding: 1) multiplying the data vector by a random number before saving it to a sacc file 2) full Muir et al implementation. We can use 1) right away while we work on 2).

**Comment by slosar** [comment]
So, the Muir recipe is additive, is this the right approach or do you want to make them multiplicative (i.e. performing Muir et al in log of measrurements)? I'm actually not sure, it does seem like the arguments for either (also dependening on what do you think you leading systematics are).

I think implementing this could be a nice hack day project.

**Comment by slosar** [comment]
I have now read Muir et al again more carefully and I agree with them that the shifts should be additive...

**Comment by chihway** [comment]
A possible way to do this:
- call `firecrown compute` twice, with different parameters
- generate delta data vector from the two sacc files above
- add to txpipe two-point

Alternatively, call CCL
see:  https://github.com/LSSTDESC/TXPipe/blob/master/txpipe/plotting/correlations.py

**Comment by chihway** [comment]
This is in TXPipe now. https://github.com/LSSTDESC/TXPipe/pull/63. 
Closing.
