### ISSUE TITLE
HSC Fourier 3x2pt: raw data reduction issues

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/txpipe-reanalysis#21]
- [x] Check in detail that the right cuts are being implemented in the data reduction script.
- [x] Current default redshift bins don't match those used in the HSC analysis
- [x] Include the possibility of imposing magnitude cuts in selector stages (rather than reduction script)

**Comment by fjaviersanchez** [comment]
This was done at https://github.com/LSSTDESC/TXPipe/pull/135
